[build]
  publish = ""
  command = ""

[context.production]
  publish = ""
  command = ""

# [[headers]]
#   for = "/*"

#   [headers.values]
#     cache-control = "max-age=7200"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
