[build]
  publish = "/platforms/docs/.next"
  command = "npm install && npm run bootstrap && npm run docs"

[context.production]
  publish = ""
  command = ""

# [[headers]]
#   for = "/*"

#   [headers.values]
#     cache-control = "max-age=7200"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
