name: After Test
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  upload_codacy:
    name: upload codacy
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      # Download site artifact
      - name: download coverage artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: coverage

      - name: codacy-coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}