name: Auto Assign
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  add-reviews:
    name: add reviews
    runs-on: ubuntu-latest
    steps:
      - name: auto-assign
        uses: kentaro-m/auto-assign-action@v1.2.4
        # with:
        #   configuration-path: '.github/some_name_for_configs.yml' # Only needed if you use something other than .github/auto_assign.yml
