name: Codacy Analysis CLI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          # tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
          verbose: true
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
