name: Codacy Analysis

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: perform analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          # tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
