name: deploy website
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: lerna bootstrap
        run: npm run bootstrap -- --no-ci

      - name: build docs
        run: cd ./platforms/docs/ && npm run build

      - name: netlify config
        run: cp ./netlify.toml ./platforms/docs/dist
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./platforms/docs/dist
          emptyCommits: false
