name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: bootstrap
        run: npm run bootstrap -- --no-ci

      - name: run lint
        run: npm run lint

  build_library:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: bootstrap
        run: npm run bootstrap  -- --no-ci

      - name: build library
        run: npm run build

  build_docs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: bootstrap
        run: npm run bootstrap  -- --no-ci

      - name: build docs
        run: npm run docs

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: bootstrap
        run: npm run bootstrap  -- --no-ci

      - name: run test
        run: npm run test -- --coverage --bail

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: codacy-coverage
        if: ${{ github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}

      - name: upload coverage artifact
        if: ${{ github.event_name == 'push_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
          retention-days: 5
