name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run lint
        run: npm run lint:all

  build_library:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build library
        run: npm run build

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build docs
        run: npm run docs
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run test
        run: JEST_JUNIT_CLASSNAME="{filepath}" npm run test -- --coverage --reporters=default --reporters=jest-junit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: codacy-coverage
        if: ${{ github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}

      - name: upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 5
