name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v14.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run lint
        run: npm run lint

  build_library:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v14.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build library
        run: npm run build

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v14.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build docs
        run: npm run docs
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v14.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run test
        run: npm run test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: codacy-coverage
        if: ${{ github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}

      - name: upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
          retention-days: 5
