name: Version Update
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['prerelease', 'patch']
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create changes
        run: |
          export RELEASE_TYPE=${{matrix.type}}
          node ./scripts/createVersion.js

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: version/${{matrix.type}}
          force: true

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'version/${{matrix.type}}' # If blank, default: triggered branch
          destination_branch: 'master' # If blank, default: master
          pr_title: 'merge: merge version/${{matrix.type}} into master' # Title of pull request
          pr_body: ':crown: *An automated PR*' # Full markdown support, requires pr_title to be set
          # pr_template: '.github/PULL_REQUEST_TEMPLATE.md' # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: 'rhysxia' # Comma-separated list (no spaces)
          pr_assignee: 'rhysxia' # Comma-separated list (no spaces)
          pr_label: 'version' # Comma-separated list (no spaces)
          # pr_milestone: 'Milestone 1' # Milestone name
          # pr_draft: true # Creates pull request as draft
          # pr_allow_empty: true # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
